name: "Question Form"
title: "[Question]: "
description: "Ask a question within a public forum"
labels: ["status:waiting", "type:question"]
assignees: ["brycekwon"]
body:
  - type: textarea
    id: question_description
    attributes:
      label: Question Description
      description: Provide a clear and concise description of your question.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any relevant screenshots, logs, or other context.
    validations:
      required: false
